---
title: "broch18-01-preprocess_data"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: github_document
params:
  name: "broch18-01-preprocess_data" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "6972c0f1-021c-4d3e-aa4d-2d9ea032c76e")
```

The purpose of this document is ...

```{r packages}
library("tidyverse")
library("DGrowthR")
```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = TRUE)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```


## Read Data. 

```{r read.data}

ecbw_od <- read_tsv(path_source("broch18-00-import_data", "ecoli_od_BW.tsv.gz"), show_col_types = FALSE)
ecbw_metadata <- read_tsv(path_source("broch18-00-import_data", "ecoli_metadata_BW.tsv.gz"), show_col_types = FALSE)

eciai_od <- read_tsv(path_source("broch18-00-import_data", "ecoli_od_iAi.tsv.gz"), show_col_types = FALSE)
eciai_metadata <- read_tsv(path_source("broch18-00-import_data", "ecoli_metadata_iAi.tsv.gz"), show_col_types = FALSE)

```
  
18 is the smallest number of timepoints, consider only the first 18 timepoints

```{r filter.tps}
ecbw_od <- ecbw_od %>% 
  filter(timepoint_n <= 18)


eciai_od <- eciai_od %>% 
  filter(timepoint_n <= 17)
```

  
## Create DGrowthR objects
  
```{r creat.obj}

dgobj.ecbw <-  new("DGrowthR", 
                od_data = ecbw_od, 
                metadata = ecbw_metadata,
                raw_od = ecbw_od,
                verbose=TRUE)



dgobj.eciai <-  new("DGrowthR", 
                od_data = eciai_od, 
                metadata = eciai_metadata,
                raw_od = eciai_od,
                verbose=TRUE)


```


## View raw growth curves. 
 
```{r raw.gc}

plot_growth_curves(dgobj.ecbw) +
  labs(title = "E.coli BW")

plot_growth_curves(dgobj.eciai) +
  labs(title = "E.coli IAI1")
```

## Standard pre-processing. 
 
```{r prep}
dgobj.ecbw.logged <-  preprocess_data(dgobj.ecbw, 
                                      skip_first_n_timepoints = 2,
                                      baseline = 3)

dgobj.eciai.logged <-  preprocess_data(dgobj.eciai, 
                                       skip_first_n_timepoints = 2,
                                       baseline = 3)


dgobj.ecbw.linear <-  preprocess_data(dgobj.ecbw, 
                                      skip_first_n_timepoints = 2,
                                      baseline = 3,
                                      log_transform = FALSE) 

dgobj.eciai.linear <-  preprocess_data(dgobj.eciai, 
                                       skip_first_n_timepoints = 2,
                                       baseline = 3,
                                      log_transform = FALSE)
```


```{r log.prepped}
plot_growth_curves(dgobj.ecbw.logged) +
  labs(title = "E.coli BW")

plot_growth_curves(dgobj.eciai.logged) +
  labs(title = "E.coli IAI1")
```


```{r linear.prepped}
plot_growth_curves(dgobj.ecbw.linear) +
  labs(title = "E.coli BW")

plot_growth_curves(dgobj.eciai.linear) +
  labs(title = "E.coli IAI1")
```
## Write objects

```{r write.objects}
saveRDS(dgobj.ecbw, path_target("dgobj_ecbw.rds"))
saveRDS(dgobj.ecbw.logged, path_target("dgobj_ecbw_logged.rds"))
saveRDS(dgobj.ecbw.linear, path_target("dgobj_ecbw_linear.rds"))


saveRDS(dgobj.eciai, path_target("dgobj_iai.rds"))
saveRDS(dgobj.eciai.logged, path_target("dgobj_iai_logged.rds"))
saveRDS(dgobj.eciai.linear, path_target("dgobj_iai_linear.rds"))

```


## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```

## Session Info

```{r}
sessionInfo()
```

